config:
  target: http://10.43.244.164:3001
  phases:
    - duration: 30
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 60
      arrivalRate: 10
      rampTo: 25
      name: Ramp up load
    - duration: 30
      arrivalRate: 20
      rampTo: 60
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
scenarios:
  - flow:
      - loop:
        # - get:
        #     url: "/"
        - post:
            url: "/test"
            headers:
              x-user-id: "test|123"
            json:
              message: "Hello, World!"
        count: 10