config:
  target: http://10.43.63.25:3001
  phases:
    - duration: 30
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 60
      arrivalRate: 10
      rampTo: 35
      name: Ramp up load
    - duration: 100
      arrivalRate: 35
      rampTo: 200
      name: Spike phase
  # Load & configure a couple of useful plugins
  # https://docs.art/reference/extensions
  plugins:
    apdex: {}
    metrics-by-endpoint: {}
  apdex:
    threshold: 100
scenarios:
  - flow:
      - loop:
        - post:
            url: "/dm"
            headers:
              x-user-id: "test|123"
            json:
              message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
              receiver_id: "test|456"
        - get:
            url: "/dm/test|456"
            headers:
              x-user-id: "test|123"
        - think: 1
        count: 30

