name: deploy to Azure Kubernetes Service (AKS) by restarting and pulling the new image

env:
    PROJECT_NAME: pixelchat-message-api
    RESOURCE_GROUP: PixelChat_US
    CLUSTER_NAME: PixelChat-Cluster

on:
    push:
        branches:
            - develop
    workflow_run:
        workflows: ["docker-push"]
        types: 
            - completed
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: login to kubectl
          run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }}
        - name: restart the container
          run: kubectl rollout restart deployment ${{ env.PROJECT_NAME }}
        - name: wait for the deployment to finish
          run: kubectl wait --for=condition=available --timeout=600s deployment/${{ env.PROJECT_NAME }}
